[features]
seeds = false
skip-lint = false

[programs.localnet]
baggage = "9aaJ19ZKGUoGQDkzHVFVyhpK7iAviedofonxiT3Ayz81"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ranger/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types/"
members = [
    "programs/*"
]

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.account]]
address = "9aaJ19ZKGUoGQDkzHVFVyhpK7iAviedofonxiT3Ayz81"
filename = "target/deploy/baggage-keypair.json"
size = 1024000
