[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
baggage = "Bo21goLpUivUVo7XPUTLz2sL4uvCouWv93D47a9MvB6H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[test.validator]
url = "http://127.0.0.1:8899"
commitment = "confirmed"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit.ts"
